local_backend: true

backend:
  name: git-gateway
  repo: prachtsaal/prachtsaal.berlin
  branch: main # Branch to update (optional; defaults to master)

media_folder: "assets/img" 

collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "About page"
        name: "about"
        file: "/about.md"
        fields: 
          - {label: Title, name: title, widget: string}
          - {label: Body, name: body, widget: markdown}
      - label: "Impressum"
        name: "impressum"
        file: "/impressum.md"
        fields: 
          - {label: Title, name: title, widget: string}
          - {label: Body, name: body, widget: markdown}
      - label: "Home page"
        name: "home"
        file: "/index.md"
        fields: 
          - {label: Title, name: title, widget: string}
          - {label: Subtitle, name: subtitle, widget: string}
          - {label: Body, name: body, widget: markdown}
  - name: "members" # Used in routes, e.g., /admin/collections/members
    label: "Members" # Used in the UI
    identifier_field: full_name
    folder: "_members" # The path to the folder where the documents are stored
    media_folder: '../{{media_folder}}/members/{{slug}}/'
    public_folder: '/assets/img/members/{{slug}}/'
    create: true # Allow users to create new documents in this collection
    slug: "{{ slug }}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { 
        label: "Layout", 
        name: "layout", 
        widget: "hidden", 
        default: "member" 
      }
      - { 
        label: "Current Member", 
        name: "current", 
        widget: "boolean", 
        default: true 
      }
      - { 
        label: "Full Name", 
        name: "full_name", 
        widget: "string" 
      }
      - { 
        label: "Description", 
        name: "description", 
        widget: "string", 
        hint: "Visual artist? Sound artist?" 
      }
      - { 
        label: "Thumbnail Image", 
        name: "thumb", 
        widget: "image", 
        required: false, 
        hint: "Square image, 400x400, webp format, shown in the People list" 
      }
      - { 
        label: "Portrait", 
        name: "portrait", 
        widget: "image", 
        required: false,
        hint: "Portrait displayed in the artist's page. Max 1920x1920, webp format."
      }
      - { 
        label: "Portfolio Images", 
        name: "portfolio_image_locations", 
        widget: "list", 
        field: {
          label: Portfolio Image, 
          name: image, 
          widget: image,
        },
        hint: "Artwork examples. Max 1920x1920, webp format."
      }
      - { 
        label: "Website", 
        name: "website", 
        widget: "string", 
        required: false,
        hint: "If provided, starts with https://"
      }
      - { 
        label: "Social links", 
        name: "socials", 
        widget: "list",
        field: { label: "URL", name: "url", widget: "string" }
      }
      - { 
        label: "Body", 
        name: "body", 
        widget: "markdown", 
        required: false 
      }

  # - name: "events" # Used in routes, e.g., /admin/collections/blog
  #   label: "Events" # Used in the UI
  #   folder: "events/_posts" # The path to the folder where the documents are stored
  #   create: true # Allow users to create new documents in this collection
  #   slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
  #   fields: # The fields for each document, usually in front matter
  #     - { label: "Layout", name: "layout", widget: "hidden", default: "event" }
  #     - { label: "Title", name: "title", widget: "string" }
  #     - { label: "Subtitle", name: "subtitle", widget: "string" }
  #     - { label: "Main Image", name: "main_image", widget: "image" }
  #     - { label: "Description", name: "description", widget: "string" }
  #     - { label: "Start Date", name: "start_date", widget: "string" }
  #     - { label: "Quote", name: "quote", widget: "string" }
  #     - { label: "Quote Author", name: "quote_author", widget: "string" }
  #     - { label: "Quote Author Role", name: "quote_author_role", widget: "string" }
  #     - { label: "Images", name: "images", widget: "object" }
  #       - { label: "File", name: "images", widget: "object" }
  #       - { label: "Caption", name: "images", widget: "object" }
  #     - { label: "Link", name: "link", widget: "string" }
  #     - { label: "Link Text", name: "link_text", widget: "string" }
  #     - { label: "Tags", name: "tags", widget: "string" }
  #     - { label: "Body", name: "body", widget: "markdown" }

  # - name: "news" # Used in routes, e.g., /admin/collections/blog
  #   label: "News" # Used in the UI
  #   folder: "news/_posts" # The path to the folder where the documents are stored
  #   create: true # Allow users to create new documents in this collection
  #   slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
  #   fields: # The fields for each document, usually in front matter
  #     - { label: "Layout", name: "layout", widget: "hidden", default: "blog" }
  #     - { label: "Title", name: "title", widget: "string" }
  #     - { label: "Publish Date", name: "date", widget: "datetime" }
  #     - { label: "Featured Image", name: "thumbnail", widget: "image" }
  #     - { label: "Rating (scale of 1-5)", name: "rating", widget: "number" }
  #     - { label: "Body", name: "body", widget: "markdown" }
