local_backend: true

backend:
  name: git-gateway
  repo: prachtsaal/prachtsaal.berlin
  branch: main # Branch to update (optional; defaults to master)

media_folder: "assets/img" 

collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Home page"
        name: "home"
        file: "/index.md"
        fields: 
          - {label: Title, name: title, widget: string}
          - {label: Subtitle, name: subtitle, widget: string}
          - {label: Body, name: body, widget: markdown}
      - label: "About page"
        name: "about"
        file: "/about.md"
        fields: 
          - {label: Title, name: title, widget: string}
          - {label: Body, name: body, widget: markdown}
      - label: "Impressum"
        name: "impressum"
        file: "/impressum.md"
        fields: 
          - {label: Title, name: title, widget: string}
          - {label: Body, name: body, widget: markdown}

  - name: "events" # Used in routes, e.g., /admin/collections/events
    label: "Events" # Used in the UI
    identifier_field: title
    folder: "_events" # The path to the folder where the documents are stored
    media_folder: '../{{media_folder}}/events/{{start_date}}-{{slug}}/'
    public_folder: '/assets/img/events/{{start_date}}-{{slug}}/'
    create: true # Allow users to create new documents in this collection
    slug: "{{start_date}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - label: "Layout" 
        name: "layout"
        hidden: true
        default: "event" 
      
      - label: "Title"
        name: "title"
        widget: "string" 
      
      - label: "Subtitle"
        name: "subtitle"
        widget: "string"
        required: false
      
      - label: "Description"
        name: "description"
        widget: "string"
        required: false
      
      - label: "Start Date"
        name: "start_date"
        widget: "datetime" 
        date_format: "YYYY-MM-DD"
      - label: "End Date"
        name: "end_date"
        widget: "datetime" 
        date_format: "YYYY-MM-DD"

      - label: "Featured Image"
        name: "main_image"
        widget: "image"
        required: false
      
      - label: "Images"
        name: "images" 
        widget: "list"
        required: false
        fields: 
          - {label: Image, name: image, widget: image}
          - {label: Caption, name: caption, widget: string}
    
      - label: "Tags"
        name: "tags"
        widget: "select"
        required: false
        multiple: true
        options: ["portfolio"]
        
      - label: "Body"
        name: "body"
        widget: "markdown"
        required: false 

  - name: "news" # Used in routes, e.g., /admin/collections/news
    label: "News" # Used in the UI
    identifier_field: title
    folder: "_news" # The path to the folder where the documents are stored
    media_folder: '../{{media_folder}}/events/{{start_date}}-{{event_title}}/'
    public_folder: '/assets/img/events/{{start_date}}-{{event_title}}/'
    create: true # Allow users to create new documents in this collection
    slug: "{{publish_date}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - label: "Layout" 
        name: "layout"
        hidden: true
        default: "event" 
      
      - label: "Title"
        name: "title"
        widget: "string" 
      
      - label: "Subtitle"
        name: "subtitle"
        widget: "string"
        required: false
      
      - label: "Description"
        name: "description"
        widget: "string"
        required: false
      
      - label: "Publish Date"
        name: "publish_date"
        widget: "datetime" 
        date_format: "YYYY-MM-DD"
        default: "{{now}}"

      - label: "Event Title"
        name: "event_title"
        widget: "string" 
      - label: "Event Start Date"
        name: "start_date"
        widget: "datetime" 
        date_format: "YYYY-MM-DD"
      - label: "Event End Date"
        name: "end_date"
        widget: "datetime" 
        date_format: "YYYY-MM-DD"

      - label: "Featured Image"
        name: "main_image"
        widget: "image"
        required: false

      - label: "Featured caption"
        name: "featured_caption"
        widget: string
        required: false
      
      - label: "Images"
        name: "images" 
        widget: "list"
        required: false
        fields: 
          - {label: Image, name: image, widget: image}
          - {label: Caption, name: caption, widget: string}
    
      - label: "Tags"
        name: "tags"
        widget: "hidden"
        default: "news"
        
      - label: "Body"
        name: "body"
        widget: "markdown"
        required: false 

  - name: "members" # Used in routes, e.g., /admin/collections/members
    label: "Members" # Used in the UI
    identifier_field: full_name
    folder: "_members" # The path to the folder where the documents are stored
    media_folder: '../{{media_folder}}/members/{{slug}}/'
    public_folder: '/assets/img/members/{{slug}}/'
    create: true # Allow users to create new documents in this collection
    slug: "{{ slug }}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { 
        label: "Layout", 
        name: "layout", 
        widget: "hidden", 
        default: "member" 
      }
      - { 
        label: "Current Member", 
        name: "current", 
        widget: "boolean", 
        default: true 
      }
      - { 
        label: "Full Name", 
        name: "full_name", 
        widget: "string" 
      }
      - { 
        label: "Description", 
        name: "description", 
        widget: "string", 
        hint: "Visual artist? Sound artist?" 
      }
      - { 
        label: "Thumbnail Image", 
        name: "thumb", 
        widget: "image", 
        required: false, 
        hint: "Square image, 400x400, webp format, shown in the People list" 
      }
      - { 
        label: "Portrait", 
        name: "portrait", 
        widget: "image", 
        required: false,
        hint: "Portrait displayed in the artist's page. Max 1920x1920, webp format."
      }
      - { 
        label: "Portfolio Images", 
        name: "portfolio_image_locations", 
        widget: "list", 
        field: {
          label: Portfolio Image, 
          name: image, 
          widget: image,
        },
        hint: "Artwork examples. Max 1920x1920, webp format."
      }
      - { 
        label: "Website", 
        name: "website", 
        widget: "string", 
        required: false,
        hint: "If provided, starts with https://"
      }
      - { 
        label: "Social links", 
        name: "socials", 
        widget: "list",
        field: { label: "URL", name: "url", widget: "string" }
      }
      - { 
        label: "Body", 
        name: "body", 
        widget: "markdown", 
        required: false 
      }
