name: Build and deploy main
on:
  push:
    branches:
      - main
  workflow_dispatch:  # allows manual trigger

permissions:
  contents: write

concurrency: ci-${{ github.ref }}

jobs:
  deploy:
    name: Build and deploy website
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Install Zola
        uses: taiki-e/install-action@v2
        with:
          tool: zola@0.22.1
      - name: Build
        run: zola build
      - name: Deploy to Github Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: public
          branch: gh-pages
          clean-exclude: pr-preview
          force: false
