name: Deploy PR CI
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed
permissions:
  contents: write
  pull-requests: write

jobs:
  deploy-preview:
    name: Deploy website PR review
    concurrency: preview-${{ github.ref }}
    runs-on: ubuntu-latest
    env:
      BASEURL: /pr-preview/pr-${{ github.event.number }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.5'
          bundler-cache: true

      - name: Build static site
        run: bundle exec jekyll build --baseurl ${{ env.BASEURL }} 

      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: _site
          preview-branch: gh-pages
          umbrella-dir: pr-preview
