name: Teardown PR Deployment
on:
  pull_request:
    types:
      - closed
      - removed
jobs:
  release:
    name: Teardown website
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install surge
        run: npm install -g surge
      - name: Teardown
        run: surge teardown ${{ vars.SURGE_PREFIX }}-${{ github.head_ref }}.${{ vars.SURGE_DOMAIN }} --token ${{ secrets.SURGE_TOKEN }}
